package controller;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.teretana.dao.ClanRepository;
import com.teretana.model.Clan;



@Controller    // This means that this class is a Controller
@RequestMapping(path="/clan") // This means URL's start with /demo (after Application path)
public class ClanController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ClanRepository clanRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewClan (@RequestParam String ime
			, @RequestParam String prezime, @RequestParam String mail) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Clan n = new Clan();
		n.setIme(ime);
		n.setPrezime(prezime);
		n.setMail(mail);
		clanRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Clan> getAllClan() {
		// This returns a JSON or XML with the users
		return clanRepository.findAll();
	}
}
